### ISSUE TITLE
NPE caused by Troubleshooting Band with no WTF/YAY events

### ISSUE THREAD

**Issue by accolasia** [openmastery/ideaflow#86]
There are a number of unexpected characteristics in the data that aren't getting processed correctly...

First, the same events are getting duplicated in the database with different ids.

<img width="1215" alt="screenshot 2017-04-02 12 55 35" src="https://cloud.githubusercontent.com/assets/2080316/24589641/ade0dd68-17a3-11e7-9e6e-3f3885b10007.png">

The effect of this is not causing an explosion, but all the duplicates cause 0 duration painCycles.

<img width="464" alt="screenshot 2017-04-02 12 57 04" src="https://cloud.githubusercontent.com/assets/2080316/24589681/3535ce90-17a4-11e7-9b7b-b5aece28f73f.png">

**Comment by Blackbaud-MikeLueders** [comment]
@accolasia i think this can be closed.. https://github.com/openmastery/ideaflow/pull/92 will fix the npe and there's another issue re: the duplicate events
