### ISSUE TITLE
Data is getting duplicated when sent to the server 2x

### ISSUE THREAD

**Issue by accolasia** [openmastery/ideaflow#88]
Events, Execs, and everything else that gets sent to the server multiple times ends up duplicated on the server with unique ids.

<img width="1317" alt="screenshot 2017-04-02 13 22 21" src="https://cloud.githubusercontent.com/assets/2080316/24589878/e131794e-17a7-11e7-813f-7a9a52b571f0.png">

**Comment by accolasia** [comment]
Use case:
Multiple Intellij windows both sending data to the server, in this case, each window is configured with multiple keys.  I've got Webstorm, and 2 different versions of Intellij running at the same time.

**Comment by mlueders** [comment]
should be fixed by https://github.com/openmastery/plugins/commit/e78369cf5e9f17658101abd432391c84d1cf986d
